name: deploy latest

on:
  release:
    types:
      - edited

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: event
        env:
          ACTION: ${{ github.event.action }}
        run: echo "::notice title=Release-Action::$ACTION"
      - name: all
        env:
          GONZ: ${{ toJSON(github.event) }}
        run: |
          echo "$GONZ"
          {
            echo "## event (${{ github.event.action }})"
            echo '```json'
            echo "$GONZ"
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
      - name: release payload
        env:
          RELEASE: ${{ toJSON(github.event.release) }}
        run: |
          echo "$RELEASE"
          {
            echo "## release payload (${{ github.event.action }})"
            echo '```json'
            echo "$RELEASE"
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
      - name: changes payload
        env:
          CHANGES: ${{ toJSON(github.event.changes) }}
        run: |
          echo "$CHANGES"
          {
            echo "## changes (only set on edited)"
            echo '```json'
            echo "$CHANGES"
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
